#============
#CREWS CONFIG
#============

#Crew Values
max-members: 12 #Maximum amount of crew members (changing might break something)
teleport-delay: 3 #Teleport delay for compound
commands-per-page: 5 #Commands per page for /crews
warp-price: 0 #Cost to warp to compound
set-compound-cost: 50 #Cost to set the crew compound
rename-cost: 100 #Cost to rename your crew name
upgrade-chat-cost: 250 #Cost to get the crew chat upgrade
upgrade-mail-cost: 250 #Cost to get the crew mail upgrade
upgrade-discord-cost: 250 #Cost to get the crew discord upgrade
influence-per-player: 300 #Amount of influence per player in crew

#Messages
#TextComponents
already-in-crew: "&#E57373You are already in a crew! &#E5CB70To leave use '/crews leave'"
can-not-invite-self: "&#E57373You can not invite yourself!"
cant-kick-boss: "&#E57373The boss can not be kicked!"
cant-kick-same-rank: "&#E57373You can not kick enforcers!"
choose-different-name: "&#E57373Please choose a different name!"
crew-is-max-level: "&#E57373The crew is already &#dfff00Max Level!"
crew-no-compound: "&#E57373The crew does not have a compound set! &#E5CB70Use '/crews setcompound'"
crew-not-found: "&#E57373Crew not found!"
crew-chat-enabled: "&#60E462Crew chat enabled!"
crew-chat-disabled: "&#E46060Crew chat disabled!"
crew-only-alphabetical: "&#E57373Crew names must only contain letters!"
crew-between-4-and-16: "&#E57373Crew names must be between 4 and 16 characters!"
compound-removed: "&#E5CB70Crew compound successfully removed!"
compound-exists: "&#E46060The crew compound already exists!"
compound-set: "&#60E462Crew compound successfully set!"
full-inventory: "&#E57373Your inventory is full!"
incorrect-crew: "&#E57373You are not in that crew!"
max-level-limit-enforcer: "&#E57373You have reached your crew enforcer limit!"
must-be-boss: "&#E57373You must be the boss to do this!"
must-be-higherup: "&#E57373You must be enforcer or boss to do this!"
no-invite: "&#E57373You do not have an invite from this crew!"
name-taken: "&#E57373That crew name is already in use!"
no-permission: "&#E57373No permission!"
must-be-in-crew: "&#E57373You must be in a crew to use this command!"
not-your-crew: "&#E57373You are not in that crew!"
not-enough-in-vault: "&#E57373You do not have enough in the crew vault to do this!"
player-not-found: "&#E57373Player not found!"
player-not-enforcer: "&#E57373This player is not an enforcer!"
please-wait-tp: "&#E57373Please wait to teleport!"
msg-success: "&#60E462Success!"
transfer-ownership: "&#E57373There are still active crew members! &#E5CB70Please transfer ownership before doing this '/crews ownership'"
can-not-demote-self: "&#E57373You can not demote yourself! &#E5CB70Use '/crews ownership' to transfer the boss rank!"
can-not-promote-self: "&#E57373You can not promote yourself!"
you-are-boss: "&#E57373Player not found!"
you-are-enforcer: "&#60E462You are the new crew boss!"
enforcer-demote: "&#E57373You have been demoted!"
need-more-sponge: "&#E57373You need more sponge in your inventory to do this!"
invalid-amount: "&#E57373Please enter a valid amount!"

#Strings
already-invited: "&#E24949{player} &#E57373already has an active invite!"
already-enforcer: "&#E24949{player} &#E57373is already an enforcer!"
crew-disband: "&#6E6363{crew} &#3B3333has been disbanded!"
crew-founded: "&#3973B1The &#7298C2{crew} &#3973B1crew has been founded!"
max-enforcer: "&#E57373The crew currently has an enforcer limit of &#E5CB70{limit}!"
joined-crew: "&#60E462{player} &#32B834has joined the crew!"
kicked-from-crew: "&#E57373{player} &#E24949has been kicked from the crew!"
leave-crew: "&#E57373{player} &#E24949has left the crew!"
new-boss: "&#606AA2{player} &#3F51B5is the new crew boss!"
new-enforcer: "&#8FCED6{player} &#80DEEAhas been promoted to enforcer!"
sponge-deposit: "&#60E462You have deposited &#3CC33E{amount} &#60E462sponge into the crew vault!"
sponge-withdraw: "&#E5CB70You have withdrawn &#B59A3B{amount} &#E5CB70sponge from the crew vault!"
player-in-crew: "empty"
player-not-in-same-crew: "&#E57373{player} &#E24949is not in the same crew as you!"
player-not-online: "&#E57373{player} &#E24949is not online!"
player-not-free-agent: "&#E57373{player} &#E24949is already in a crew!"
player-enforcer-demote: "&#E57373{player} &#E24949has been demoted from enforcer!"
upgrade-not-unlocked: "&eThe crew &#dfff00{upgrade} &eupgrade is not unlocked! &6'/crews shop'"
upgrade-already-unlocked: "&eThe crew &#dfff00{upgrade} &eupgrade is already unlocked!"
reached-max-members: "&#E57373The crew has reached its current maximum number of {limit} members!"
add-to-vault: "&a(&2{player}&a) &6Crew Vault: &#72E373{current_amount} &2(&a+{amount}&2) &#606660= &#2BBC2B{new_amount}"
remove-from-vault: "&6(&e{player}&6) &6Crew Vault: &#E3D272{current_amount} &4(&c-{amount}&4) &#606660= &#DD8425{new_amount}"
