#============
#CREWS CONFIG
#============

#Crew Values
max-members: 12 #Maximum amount of crew members (changing might break something)
teleport-delay: 3 #Teleport delay for compound
commands-per-page: 5 #Commands per page for /crews
warp-price: 0 #Cost to warp to compound
set-compound-cost: 50 #Cost to set the crew compound
rename-cost: 100 #Cost to rename your crew name
upgrade-chat-cost: 250 #Cost to get the crew chat upgrade
upgrade-mail-cost: 250 #Cost to get the crew mail upgrade
upgrade-discord-cost: 250 #Cost to get the crew discord upgrade
influence-per-player: 100 #Amount of influence per player in crew
default-rating: 1000 #new crew elo rating
max-vault-amount: 7500 #max amount sponges in vault

#Skirmish Values
arena-radius: 15 #Radius of arenas subject to cehange
wall-buffer: 5 #Space between player and border where glass will show
wall-height: 10 #Height of the barrier shown
wall-width: 10 #Width of the barrier shown

#Multiplie
#Passive Mobs
mob-multipliers:
    passive-multipliers:
        CAT: 1.5
    neutral-multipliers:
        CAVE_SPIDER: 1.5
    hostile-multipliers:
        BLAZE: 1.5

#High Table

#Messages
#TextComponents
already-in-crew: "&#E57373You are already in a crew! &#E5CB70To leave use '/crews leave'"
already-in-queue: "&#E57373Your crew is already in the skirmish queue! &#E5CB70To leave use '/c skirmish queue leave'"
can-not-invite-self: "&#E57373You can not invite yourself!"
cant-kick-boss: "&#E57373The boss can not be kicked!"
cant-kick-same-rank: "&#E57373You can not kick enforcers!"
cant-kick-self: "&#E57373You can not kick yourself!"
choose-different-name: "&#E57373Please choose a different name!"
crew-is-max-level: "&#E57373The crew is already &#dfff00Max Level!"
crew-no-compound: "&#E57373The crew does not have a compound set! &#E5CB70Use '/crews setcompound'"
crew-not-found: "&#E57373Crew not found!"
crew-chat-enabled: "&#60E462Crew chat enabled!"
crew-chat-disabled: "&#E46060Crew chat disabled!"
crew-only-alphabetical: "&#E57373Crew names must only contain letters and no spaces!"
crew-between-4-and-16: "&#E57373Crew names must be between 4 and 16 characters!"
compound-removed: "&#E5CB70Crew compound successfully removed!"
compound-exists: "&#E46060The crew compound already exists!"
compound-set: "&#60E462Crew compound successfully set!"
full-inventory: "&#E57373Your inventory is full!"
incorrect-crew: "&#E57373You are not in that crew!"
joined-queue: "&#60E462You have joined the queue!"
crew-has-joined-queue: "&#F9A825A crew has joined the Skirmish queue!"
max-level-limit-enforcer: "&#E57373You have reached your crew enforcer limit!"
must-be-boss: "&#E57373You must be the boss to do this!"
must-be-higherup: "&#E57373You must be enforcer or boss to do this!"
no-invite: "&#E57373You do not have an invite from this crew!"
name-taken: "&#E57373That crew name is already in use!"
no-permission: "&#E57373No permission!"
must-be-in-crew: "&#E57373You must be in a crew to use this command!"
not-your-crew: "&#E57373You are not in that crew!"
not-enough-in-vault: "&#E57373You do not have enough in the crew vault to do this!"
one-player-required-for-queue: "&#E57373You need to select at least one member to queue!"
player-not-found: "&#E57373Player not found!"
player-not-enforcer: "&#E57373This player is not an enforcer!"
please-wait-tp: "&#E57373Please wait to teleport!"
msg-success: "&#60E462Success!"
description-set: "&#60E462New description set!"
purchase-successful: "&#60E462Purchase successful!"
transfer-ownership: "&#E57373There are still active crew members! &#E5CB70Please transfer ownership before doing this '/crews ownership'"
can-not-demote-self: "&#E57373You can not demote yourself! &#E5CB70Use '/crews ownership' to transfer the boss rank!"
can-not-promote-self: "&#E57373You can not promote yourself!"
you-are-boss: "&#3F51B5You are now the crew boss!"
you-are-enforcer: "&#60E462You are now a crew enforcer!"
enforcer-demote: "&#E57373You have been demoted!"
need-more-sponge: "&#E57373You need more sponge in your inventory to do this!"
invalid-amount: "&#E57373Please enter a valid amount!"
not-enough-deposit: "&#E57373You can only withdraw what you deposit! You have not deposited this much in the vault!"
waiting-for-matchup: "&#F9A825Waiting for a match-up... to leave type &#FFEB3B'/c skirmish queue leave'"
crew-upgrade: "&#558B2F{crew} &#43A047has upgraded to &#558B2F&lLEVEL {level}!"
vault-max-amount: "&#E57373The maximum amount of sponges in the vault is set to {amount}!"

#Strings
already-invited: "&#E24949{player} &#E57373already has an active invite!"
already-enforcer: "&#E24949{player} &#E57373is already an enforcer!"
crew-disband: "&#6E6363{crew} &#3B3333has been disbanded!"
crew-founded: "&#3973B1The &#7298C2{crew} &#3973B1crew has been founded by &#7298C2{player}!"
max-enforcer: "&#E57373The crew currently has an enforcer limit of &#E5CB70{limit}!"
joined-crew: "&#60E462{player} &#32B834has joined the crew!"
kicked-from-crew: "&#E57373{player} &#E24949has been kicked from the crew!"
leave-crew: "&#E57373{player} &#E24949has left the crew!"
you-left-crew: "&#60E462You have left the crew!"
you-got-kicked: "&#E57373You were kicked from the crew!"
new-boss: "&#606AA2{player} &#3F51B5is the new crew boss!"
new-enforcer: "&#8FCED6{player} &#80DEEAhas been promoted to enforcer!"
sponge-deposit: "&#60E462You have deposited &#3CC33E{amount} &#60E462sponge into the crew vault!"
sponge-withdraw: "&#E5CB70You have withdrawn &#B59A3B{amount} &#E5CB70sponge from the crew vault!"
player-in-crew: "empty"
player-not-in-same-crew: "&#E57373{player} &#E24949is not in the same crew as you!"
player-not-online: "&#E57373{player} &#E24949is not online!"
player-not-free-agent: "&#E57373{player} &#E24949is already in a crew!"
player-enforcer-demote: "&#E57373{player} &#E24949has been demoted from enforcer!"
upgrade-not-unlocked: "&eThe crew &#dfff00{upgrade} &eupgrade is not unlocked! &6'/crews shop'"
upgrade-already-unlocked: "&eThe crew &#dfff00{upgrade} &eupgrade is already unlocked!"
reached-max-members: "&#E57373The crew has reached its current maximum number of {limit} members!"
add-to-vault: "&a(&2{player}&a) &6Crew Vault: &#72E373{current_amount} &2(&a+{amount}&2) &#606660→ &#2BBC2B{new_amount}"
remove-from-vault: "&6(&e{player}&6) &6Crew Vault: &#E3D272{current_amount} &4(&c-{amount}&4) &#606660→ &#DD8425{new_amount}"

#Skirmish
skirmish-started: "&#BE5350A skirmish between &#EF7550{crew1} &#BE5350and &#EF7550{crew2} &#BE5350has started!"
skirmish-draw: "&#4e4b5d&l┌──[&#F4511ESKIRMISH RESULT&#4e4b5d&l]──◓\n&#4e4b5d&l│ &7&l🔰 DRAW 🔰\n&#4e4b5d&l│ &#90CAF9👥 {team1} &7VS &#EF9A9A👥 {team2}\n&#4e4b5d&l│ &7✴ Score: &8{points1} &7- &8{points2}\n&#4e4b5d&l└─────────────◓"
skirmish-ended: "&#4e4b5d&l┌──[&#F4511ESKIRMISH RESULT&#4e4b5d&l]──◓\n&#4e4b5d&l│ &#FFD33B&l🥇 WINNER: &6&l{winner} &#FFD33B&l🥇\n&#4e4b5d&l│ &#90CAF9👥 {team1} &7VS &#EF9A9A👥 {team2}\n&#4e4b5d&l│ &7✴ Score: &2{points1} &7- &4{points2}\n&#4e4b5d&l└─────────────◓"
not-in-queue: "&#E57373You are not currently in the queue!"
gained-rating: "&6&lRATING: &e{oldRating} &#FFF176(&#FFD54F+{change}&#FFF176) → &6{total}"
lost-rating: "&c&lRATING: &#EF5350{oldRating} &#FFCDD2(&#E57373-{change}&#FFCDD2) → &c{total}"
no-change-rating: "&7&lRATING: &8No change in rating."
waiting-on-confirmation: "&eMATCH FOUND: &#EF7550Waiting on a confirmation for the skirmish match! &#FFEB3B'/c skirmish accept'"
you-have-confirmed: "&#60E462You have accepted the match-up!"
player-confirmed: "&#60E462A player has accepted the match-up! &#AEE9B0(&#E1FFCF{accepted}/{total}&#AEE9B0)"
invalid-number: "&#E57373Please enter a valid integer!"
invalid-range: "&#E57373Your number must be between {min} and {max}."
crew-has-chosen-player-amount: "&#E8C23BYour crew has chosen to fight {amount} player(s)!"
enemy-has-chosen-player-amount: "&#E8C23BThe enemy crew has chosen to fight {amount} player(s)."
players-sitting-out: "&#E8C23BUnfortunately {amount} player(s) will be sitting out... this will be chosen at random"
match-cancelled-player-left: "&#E57373A player has logged out and the match has been cancelled!"
match-cancelled-did-not-accept: "&#E57373A player did not accept and the match has been cancelled!"
crew-removed-from-queue: "&#E57373Your team has been removed from the queue for not accepting the match!"
seconds-left-to-action: "&eYou have &6{seconds} &eseconds left to &e{action}"
teleporting-countdown: "&6Teleporting to the arena in &e{seconds} &6seconds..."
skirmish-starting: "&6Skirmish starting in &e{seconds} &6seconds..."
skirmish-begin: "&c&lPVP Enabled: &6Good luck!"
stay-in-bounds: "&#E57373Please stay in bounds!"
disabled-in-skirmish: "&#E57373This action is disabled while in the arena."
disabled-command-in-arena: "&#E57373This command is disabled while in the arena. If you want to leave type &#E5CB70'/c skirmish leave'"
player-will-be-banned: "&#E57373{player} &#E24949has &#E57373{seconds} seconds &#E24949to join before being removed from the skirmish!"
player-banned: "&#E57373{player} &#E24949has been removed from the skirmish for inactivity!"

#High Table Things
vote-set: "&#AB75CDYou have set your vote! &#D3B2C3Use '/crews vote' to change your vote!"
not-in-hightable: "&#E57373Your crew is not part of the high table!"
