api-version: 1.16
name: Crews
version: 1.0
author: OVClub
website: www.ovclub.gg
main: org.ovclub.crews.Crews
description: Crews plugin for OVClub
depend: [ Vault ]
commands:
    crews:
        description: Use crews
        aliases: [c, crew, crews, C, Crew, Crews]
        usage: /crews create
permissions:
    crews.player.*:
        description: Access to crews
        default: true
#  claimsponges:
#    description: Claim a sponge_icon reward
#    usage: /claimsponges
#  setsponges:
#    description: Set sponge_icon reward
#    usage: /setsponges [player] [amount]
#    permission: crews.setsponges
#  addsponges:
#    description: Ad sponge_icon reward
#    usage: /addsponges [player] [amount]
#    permission: crews.addsponges
#  beginctf:
#    description: Begin CTF Game
#    usage: /beginctf
#  crewsupdate:
#    description: Update crew scores
#    usage: /crewsupdate
#    permission: crews.update
