api-version: 1.16
name: Crews
version: 1.04
author: DiffVanilla
website: www.diffvanilla.org
main: org.diffvanilla.crews.Crews
description: Crews plugin for DiffVanilla
depend: [ Vault ]
commands:
  crews:
    description: Create crews
    usage: /crews create
#  claimsponges:
#    description: Claim a sponge_icon reward
#    usage: /claimsponges
#  setsponges:
#    description: Set sponge_icon reward
#    usage: /setsponges [player] [amount]
#    permission: crews.setsponges
#  addsponges:
#    description: Ad sponge_icon reward
#    usage: /addsponges [player] [amount]
#    permission: crews.addsponges
#  beginctf:
#    description: Begin CTF Game
#    usage: /beginctf
#  crewsupdate:
#    description: Update crew scores
#    usage: /crewsupdate
#    permission: crews.update
